// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lnqhgfrdimfjhmvdcnjv.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxucWhnZnJkaW1mamhtdmRjbmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxNTE2MzcsImV4cCI6MjA0NTcyNzYzN30.UjlwzOayEAs64_2FvJnnMboU8JJJh3WhRd08yoYZYhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);